In [19]:
import pandas as pd

In [20]:
df_protestant_canon = pd.read_csv('../resources/canons/protestant_canon.csv', encoding='utf-8-sig')
df_catholic_canon = pd.read_csv('../resources/canons/roman_catholic_canon.csv', encoding='utf-8-sig')

In [21]:
df_protestant_canon.tail()

    book_id        name  sort_index
61     1075      1_john          62
62     1076      2_john          63
63     1077      3_john          64
64     1078        jude          65
65     1079  revelation          66

In [22]:
df_catholic_canon.tail()

    book_id        name  sort_index
68     1075      1_john          69
69     1076      2_john          70
70     1077      3_john          71
71     1078        jude          72
72     1079  revelation          73

In [23]:
df_nvi = pd.read_csv('../resources/bibles/nvi.csv', delimiter=';')
df_ara = pd.read_csv('../resources/bibles/ara.csv', delimiter=';')

In [24]:
df_nvi.tail()

,book_id,version_abbreviation,chapter,number,text
31100,66,nvi,22,17,"O Espírito e a noiva dizem: ""Vem! "" E todo aqu..."
31101,66,nvi,22,18,Declaro a todos os que ouvem as palavras da pr...
31102,66,nvi,22,19,Se alguém tirar alguma palavra deste livro de ...
31103,66,nvi,22,20,"Aquele que dá testemunho destas coisas diz: ""S..."
31104,66,nvi,22,21,A graça do Senhor Jesus seja com todos. Amém.

In [25]:
# replace the book_id with the book_id from the canon. The column sort_index is equal to the book_id in the bible.
df_ara['book_id'] = df_ara['book_id'].apply(lambda x: df_protestant_canon[df_protestant_canon['sort_index'] == x]['book_id'].values[0])
df_nvi['book_id'] = df_nvi['book_id'].apply(lambda x: df_protestant_canon[df_protestant_canon['sort_index'] == x]['book_id'].values[0])

In [26]:
# Save the DataFrame to a CSV file
df_ara.to_csv('ara_verses.csv', index=False, encoding='utf-8', sep=';')
df_nvi.to_csv('nvi_verses.csv', index=False, encoding='utf-8', sep=';')

In [27]:
# count rows
print(f"ALMEIDA REVISTA E ATUALIZADA: {len(df_ara)} rows")
print(f"NOVA VERSÃO INTERNACIONAL: {len(df_nvi)} rows")

ALMEIDA REVISTA E ATUALIZADA: 31104 rows
NOVA VERSÃO INTERNACIONAL: 31105 rows